resources:
  pipelines:
    - pipeline: myPipeline  # Name of the pipeline resource
      source: 'myProject/myRepo/myPipeline'  # Project, repository, and pipeline name
      trigger: true  # Automatically trigger the pipeline


      stages:
  - stage: InvokePipeline
    jobs:
      - job: Invoke
        steps:
          - script: echo "Invoking another pipeline"
            dependsOn: myPipeline


trigger:
- none

resources:
  pipelines:
    - pipeline: cicdPipeline  # Name of the pipeline resource
      source: 'azure-pipelines.yml'  # Project, repository, and pipeline name
      trigger: true  # Automatically trigger the pipeline
    - pipeline: regionTestsSuitePipeline  # Name of the pipeline resource
      source: 'azure-pipelines-testsuites.yml'  # Project, repository, and pipeline name
      trigger: true  # Automatically trigger the pipeline      

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo "Building the project"
            displayName: 'Run build script'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - script: echo "Deploying the project"
            displayName: 'Run deploy script'
          - script: echo "Waiting for the ci-cd pipeline to complete"
            dependsOn: cicdPipeline   
          - script: echo "Waiting for the testsuites pipeline to complete"
            dependsOn: regionTestsSuitePipeline
           