parameters:
- name: azureSubscription
  type: string
  default: 'ContainerInsights_Dev_Grace'
- name: resourceGroup
  type: string
  default: 'wtd-test'
- name: deployParameters
  type: string

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |+
      az --version
      az account show
      az deployment group create `
          --resource-group ${{ parameters.resourceGroup }} `
          --name ClusterDeployment `
          --template-file ".\wip9-final.json" `
          --parameters ${{ parameters.deployParameters }}  
          
