trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building main pipeline...

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - template: azure-pipelines-template.yml
      parameters:
        azureSubscription: $(AZURESUBSCRIPTION)
        resourceGroup: ${env:RESOURCE-GROUP}
        deployParameters: ${env:PARAMETERS}
