# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription:  ContainerInsights_Dev_Grace
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      $p = ${env:PARAMETERS} 
      "Parameters: $p"
      $j = $p | convertfrom-json

      $p
      $p=$p.Substring(2, $p.Length-4)
      $ary = $p.split(",")
      $ary

      if ([string]::IsNullOrEmpty($j.azureMonitorWorkspaceLocation)) {
         write-host "'azureMonitorWorkspaceLocation' not provided..."

         $rg = (az group show -g ${env:RESOURCE-GROUP} | convertfrom-json)
         write-host "Using location '$($rg.location)' from '$($rg.name)"

        # Does the property exist?
        if ($j.azureMonitorWorkspaceLocation -eq $null) {
          write-host "Adding new 'azureMonitorWorkspaceLocation' property..."
          $newBlock = @{value = $($rg.location)}
          $n = $newblock | convertto-json -compress

          """azureMonitorWorkspaceLocation"":$n"
          $ary += """azureMonitorWorkspaceLocation"":$n"

          ##$j | Add-Member -name "azureMonitorWorkspaceLocation" -MemberType NoteProperty -value $newBlock
        } else {
          write-host "Updating existing 'azureMonitorWorkspaceLocation' property..."
          $j.azureMonitorWorkspaceLocation = $rg.location
        }
      } else {
         write-host "'azureMonitorWorkspaceLocation' = $($j.azureMonitorWorkspaceLocation)"
      }

      ##$pp = $j | convertto-json -Compress
      $pp = [string]::join(",", $ary)
      $pp = "'{$pp}'"
      "Final parameters: $pp"

      az --version
      az account show
      az deployment group create `
          --resource-group ${env:RESOURCE-GROUP} `
          --name ClusterDeployment `
          --template-file ".\wip9-final.json" `
          --parameters $pp    ##${env:PARAMETERS}   
          
