trigger:
- none

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: git clone https://github.com/wtdoble/Test.git $(Build.ArtifactStagingDirectory)
    # Publish build artifacts v1
    # Publish build artifacts to Azure Pipelines or a Windows file share.
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)' # string. Required. Path to publish. Default: $(Build.ArtifactStagingDirectory).
        ArtifactName: 'drop' # string. Required. Artifact name. Default: drop.
        publishLocation: 'Container' # 'Container' | 'FilePath'. Alias: ArtifactType. Required. Artifact publish location. Default: Container.
        #MaxArtifactSize: '0' # string. Max Artifact Size. Default: 0.
        #TargetPath: # string. Required when ArtifactType = FilePath. File share path. 
        #Parallel: false # boolean. Optional. Use when ArtifactType = FilePath. Parallel copy. Default: false.
        #ParallelCount: '8' # string. Optional. Use when ArtifactType = FilePath && Parallel = true. Parallel count. Default: 8.
        # Advanced
        #StoreAsTar: false # boolean. Tar the artifact before uploading. Default: false.
