trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building main pipeline...

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - template: azure-pipelines-template.yml
      parameters:
        azureSubscription: $(AZURESUBSCRIPTION)
        resourceGroup: $(RESOURCE-GROUP)
        deployParameters: $(PARAMETERS)

- stage: Test
  dependsOn: Deploy
  jobs:
  - job: TestJob
    steps:
    - template: azure-pipelines-testsuites-template.yml
      parameters:
        azureSubscription: $(AZURESUBSCRIPTION)
        resourceGroup: $(RESOURCE-GROUP)
        clusterName: $(CLUSTER-NAME)
